apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-node-example
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld      
    spec:    
      containers:
      - name: k8s-node-example
        image: jorgedutton/k8s-node-example
        ports:
        - containerPort: 3000	