apiVersion: v1
kind: Pod
metadata:
  name: k8s-node-example
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-node-example
    image: jorgedutton/k8s-node-example
    ports:
    - name: nodejs-port
      containerPort: 3000	  